name: codepan
description: General purpose library for dart.
version: 1.0.1
author: Jeffrey Concha
homepage: https://github.com/jeffreyconcha/codepan.git

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite_sqlcipher: ^1.1.1
  intl: ^0.16.1
  video_player: ^0.10.11+2
  audioplayer: ^0.8.1
  flutter_svg: ^0.18.1
  time_ago_provider: ^2.0.5
  visibility_detector: ^0.1.5
  path_provider: ^1.6.11
  flutter_bloc: ^6.0.1
  connectivity: '>=0.4.8+6 <2.0.0'
  pull_to_refresh: ^1.6.0
  cached_network_image: ^2.2.0+1
  html_unescape: ^1.0.2
  equatable: ^1.1.1
  permission_handler: ^5.0.1+1
  app_settings: ^4.0.4
  exif: ^1.0.3
  image: ^2.1.19

dev_dependencies:
  flutter_test:
    sdk: flutter

  # For information on the generic Dart part of this file, see the
  # following page: https://dart.dev/tools/pub/pubspec

  # The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/icons/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:


